### ISSUE TITLE
process.env.NODE_ENV does not work after the plugin

### ISSUE THREAD

**Issue by ta3pks** [jabuco/parcel-plugin-obfuscate#1]

**Comment by peanutbother** [comment]
could you please provide a description containing expected and actual behavior?
this would help me to file a workaround, or fix and implement tests based on this issue.

**Comment by ta3pks** [comment]
I am using reasonml, elm and parcel.
When I build things only using parcel without the plugin things work just fine and things that should be stripped away or mangled work seamlessly however when I use the obfuscate plugin I start getting all sorts of errors describing things being undefined. My theory at this point is that obfuscate plugin obfuscates things too early before parcel actually handles bundling and other plugins being run.
The expected behavior would be letting parcel handle everything and as the last step to obfuscate things so things won't break

**Comment by peanutbother** [comment]
My guess is, that this behavior is due to obfuscation of global variables, which are hardcoded at some point. I will have a look a this this evening. 
can you provide an example repository with some of your code?

I will test it with some access on `global` and `proccess.env` but this might be to vanilla since I won't be able to use the same libraries etc

**Comment by ta3pks** [comment]
sure i will create a small repo and link here

**Comment by ta3pks** [comment]
[this](https://gist.github.com/NikosEfthias/5c6c453ed478acb4c83742283d152d77) is i believe the smallest possible demonstration
If you bundle it with the obfuscate plugin it will give an error otherwise it works just fine without the obfuscation.
While running  the example parcel cache prevents things being fully rebuilding if you first build with obfuscate and then without so for better result I suggest disabling cache for testing

**Comment by peanutbother** [comment]
Thank you for your help!
I will have a look into it later and will debug it as best as I can

**Comment by peanutbother** [comment]
I tried your example and it generally won't work in a standard browser since there's no `process` variable.
So I tried this using electron and it works.
We need to look closer what is not working. 
My gist with electron can be found [here](https://gist.github.com/peanutbother/1139b650b92e16517884412cf1c250e5)

**Comment by ta3pks** [comment]
@peanutbother the thing is that it is normally compiled out by parcel regardless of the environment
This is the reason I suggested that the obfuscator plugin might be doing its thing too also like the process.env other plugins when used with the obfuscate plugin fail

**Comment by peanutbother** [comment]
I looked through the documentation of [javascript-obfuscator](https://www.npmjs.com/package/javascript-obfuscator#options)
 and I there might be an error I made because I missed the option
`--target <string> [browser, browser-no-eval, node]`
which might cause trouble when building different targets.

also there is 
`-globals <boolean>`
which might also be worth experimenting.

for this issue I will especially have a look at these options:
`--reserved-names '<list>' (comma separated)`
`--reserved-strings '<list>' (comma separated)`

maybe we can solve the issue by using the last options

**Comment by ta3pks** [comment]
I still believe the main issue is parcel-plugin-obfuscate starts handling things too early preventing parcel and the default plugins to do their things. 
the `process` is not global in case of the browser if you check [here](https://parceljs.org/production.html) this is simply deleted by parcel using terser by default and at that stage obfuscator should not touch anything but it does. So that is the thing seemingly causing the issue.

So I believe this is a parcel plugin lifetime issue rather than an issue with the javascript-obfuscator js  library @peanutbother

**Comment by ta3pks** [comment]
[apparently](https://github.com/parcel-bundler/parcel/issues/4045) this is a known issue and seems to be addressed in version 2. I dont know how they improved this though. Something similar to systemd lifecycle hooks would be really useful

**Comment by annachu** [comment]
I got the same error with the `process` variable and dug into this a bit. I've submitted a pull request (#2) that should hopefully work for everyone.

**Comment by peanutbother** [comment]
pushed version 2.1.1 to npm, let me know if it fixes it.

**Comment by ta3pks** [comment]
I haven't had a chance to test it yet but seems it will breaks when used with react based on the other bug report

**Comment by peanutbother** [comment]
I tested it using a minimal index.html + index.jsx which rendered fine.
If you face issues with your code please provide a minimal repro.

**Comment by peanutbother** [comment]
And to also adress this issue: NODE_ENV and other environment variables worked too!
